name: 'Send Space Text Message'
description: 'Sends a text message to a channel in Jetbrains Space'
inputs:
  space_url:
    description: 'The URL your space is hosted at (eg: <name>.jetbrains.space)'
    required: true
  access_token:
    description: 'Personal access token for Space API.'
    required: true
  channel_id:
    description: 'The Channel ID you wish to send the messages to.'
    required: true
  message:
    description: 'The text message you wish to send.'
    required: true
outputs:
  response:
    description: 'Returns the response from the Space API.'
runs:
  using: 'node12'
  main: 'dist/index.js'
